version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: book-explorer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: book-explorer
    volumes:
      - mongodb_data:/data/db
    networks:
      - book-explorer-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: book-explorer-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:password@mongodb:27017/book-explorer?authSource=admin
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - book-explorer-network
    volumes:
      - ./backend:/app
      - /app/node_modules


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: book-explorer-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - book-explorer-network

volumes:
  mongodb_data:
    driver: local

networks:
  book-explorer-network:
    driver: bridge